// Generated by the protocol buffer compiler.  DO NOT EDIT!
//  Created by MathewWang on 15/6/4.
//  Copyright (c) 2015年 Jiamian. All rights reserved.

#import "ProtocolBuffers.h"

@class RequestHeader;
@class RequestHeader_Builder;
@class RequestMsg;
@class RequestMsg_Builder;

@interface RequestRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface RequestHeader : PBGeneratedMessage {
@private
  BOOL hasSid_:1;
  BOOL hasCid_:1;
  BOOL hasSeqNo_:1;
  int32_t sid;
  int32_t cid;
  int32_t seqNo;
}
- (BOOL) hasSid;
- (BOOL) hasCid;
- (BOOL) hasSeqNo;
@property (readonly) int32_t sid;
@property (readonly) int32_t cid;
@property (readonly) int32_t seqNo;

+ (RequestHeader*) defaultInstance;
- (RequestHeader*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RequestHeader_Builder*) builder;
+ (RequestHeader_Builder*) builder;
+ (RequestHeader_Builder*) builderWithPrototype:(RequestHeader*) prototype;

+ (RequestHeader*) parseFromData:(NSData*) data;
+ (RequestHeader*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RequestHeader*) parseFromInputStream:(NSInputStream*) input;
+ (RequestHeader*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RequestHeader*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RequestHeader*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RequestHeader_Builder : PBGeneratedMessageBuilder {
@private
  RequestHeader* result;
}

- (RequestHeader*) defaultInstance;

- (RequestHeader_Builder*) clear;
- (RequestHeader_Builder*) clone;

- (RequestHeader*) build;
- (RequestHeader*) buildPartial;

- (RequestHeader_Builder*) mergeFrom:(RequestHeader*) other;
- (RequestHeader_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RequestHeader_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSid;
- (int32_t) sid;
- (RequestHeader_Builder*) setSid:(int32_t) value;
- (RequestHeader_Builder*) clearSid;

- (BOOL) hasCid;
- (int32_t) cid;
- (RequestHeader_Builder*) setCid:(int32_t) value;
- (RequestHeader_Builder*) clearCid;

- (BOOL) hasSeqNo;
- (int32_t) seqNo;
- (RequestHeader_Builder*) setSeqNo:(int32_t) value;
- (RequestHeader_Builder*) clearSeqNo;
@end

@interface RequestMsg : PBGeneratedMessage {
@private
  BOOL hasHeader_:1;
  BOOL hasBody_:1;
  RequestHeader* header;
  NSData* body;
}
- (BOOL) hasHeader;
- (BOOL) hasBody;
@property (readonly, retain) RequestHeader* header;
@property (readonly, retain) NSData* body;

+ (RequestMsg*) defaultInstance;
- (RequestMsg*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RequestMsg_Builder*) builder;
+ (RequestMsg_Builder*) builder;
+ (RequestMsg_Builder*) builderWithPrototype:(RequestMsg*) prototype;

+ (RequestMsg*) parseFromData:(NSData*) data;
+ (RequestMsg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RequestMsg*) parseFromInputStream:(NSInputStream*) input;
+ (RequestMsg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RequestMsg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RequestMsg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RequestMsg_Builder : PBGeneratedMessageBuilder {
@private
  RequestMsg* result;
}

- (RequestMsg*) defaultInstance;

- (RequestMsg_Builder*) clear;
- (RequestMsg_Builder*) clone;

- (RequestMsg*) build;
- (RequestMsg*) buildPartial;

- (RequestMsg_Builder*) mergeFrom:(RequestMsg*) other;
- (RequestMsg_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RequestMsg_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasHeader;
- (RequestHeader*) header;
- (RequestMsg_Builder*) setHeader:(RequestHeader*) value;
- (RequestMsg_Builder*) setHeaderBuilder:(RequestHeader_Builder*) builderForValue;
- (RequestMsg_Builder*) mergeHeader:(RequestHeader*) value;
- (RequestMsg_Builder*) clearHeader;

- (BOOL) hasBody;
- (NSData*) body;
- (RequestMsg_Builder*) setBody:(NSData*) value;
- (RequestMsg_Builder*) clearBody;
@end

