// Generated by the protocol buffer compiler.  DO NOT EDIT!
//  Created by MathewWang on 15/6/4.
//  Copyright (c) 2015年 Jiamian. All rights reserved.
#import "ProtocolBuffers.h"

@class SendReq;
@class SendReq_Builder;
@class SendRes;
@class SendRes_Builder;

@interface SendRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface SendReq : PBGeneratedMessage {
@private
  BOOL hasUserName_:1;
  BOOL hasToUserName_:1;
  BOOL hasContent_:1;
  NSString* userName;
  NSString* toUserName;
  NSString* content;
}
- (BOOL) hasUserName;
- (BOOL) hasToUserName;
- (BOOL) hasContent;
@property (readonly, retain) NSString* userName;
@property (readonly, retain) NSString* toUserName;
@property (readonly, retain) NSString* content;

+ (SendReq*) defaultInstance;
- (SendReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SendReq_Builder*) builder;
+ (SendReq_Builder*) builder;
+ (SendReq_Builder*) builderWithPrototype:(SendReq*) prototype;

+ (SendReq*) parseFromData:(NSData*) data;
+ (SendReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SendReq*) parseFromInputStream:(NSInputStream*) input;
+ (SendReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SendReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SendReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SendReq_Builder : PBGeneratedMessageBuilder {
@private
  SendReq* result;
}

- (SendReq*) defaultInstance;

- (SendReq_Builder*) clear;
- (SendReq_Builder*) clone;

- (SendReq*) build;
- (SendReq*) buildPartial;

- (SendReq_Builder*) mergeFrom:(SendReq*) other;
- (SendReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SendReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserName;
- (NSString*) userName;
- (SendReq_Builder*) setUserName:(NSString*) value;
- (SendReq_Builder*) clearUserName;

- (BOOL) hasToUserName;
- (NSString*) toUserName;
- (SendReq_Builder*) setToUserName:(NSString*) value;
- (SendReq_Builder*) clearToUserName;

- (BOOL) hasContent;
- (NSString*) content;
- (SendReq_Builder*) setContent:(NSString*) value;
- (SendReq_Builder*) clearContent;
@end

@interface SendRes : PBGeneratedMessage {
@private
  BOOL hasResCode_:1;
  BOOL hasFromUserName_:1;
  BOOL hasContent_:1;
  int32_t resCode;
  NSString* fromUserName;
  NSString* content;
}
- (BOOL) hasResCode;
- (BOOL) hasFromUserName;
- (BOOL) hasContent;
@property (readonly) int32_t resCode;
@property (readonly, retain) NSString* fromUserName;
@property (readonly, retain) NSString* content;

+ (SendRes*) defaultInstance;
- (SendRes*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SendRes_Builder*) builder;
+ (SendRes_Builder*) builder;
+ (SendRes_Builder*) builderWithPrototype:(SendRes*) prototype;

+ (SendRes*) parseFromData:(NSData*) data;
+ (SendRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SendRes*) parseFromInputStream:(NSInputStream*) input;
+ (SendRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SendRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SendRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SendRes_Builder : PBGeneratedMessageBuilder {
@private
  SendRes* result;
}

- (SendRes*) defaultInstance;

- (SendRes_Builder*) clear;
- (SendRes_Builder*) clone;

- (SendRes*) build;
- (SendRes*) buildPartial;

- (SendRes_Builder*) mergeFrom:(SendRes*) other;
- (SendRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SendRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasResCode;
- (int32_t) resCode;
- (SendRes_Builder*) setResCode:(int32_t) value;
- (SendRes_Builder*) clearResCode;

- (BOOL) hasFromUserName;
- (NSString*) fromUserName;
- (SendRes_Builder*) setFromUserName:(NSString*) value;
- (SendRes_Builder*) clearFromUserName;

- (BOOL) hasContent;
- (NSString*) content;
- (SendRes_Builder*) setContent:(NSString*) value;
- (SendRes_Builder*) clearContent;
@end

